# Este código sirve para las BD con los archivos agrupados 

Lee los archivos agrupados en carpetas hechas por el código "extraer_datos.ipynb" 

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import os
import re
import matplotlib.pyplot as plt

In [6]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_entrenamiento/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_entrenamiento/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
#Linux
#matriz = np.zeros((10,199))
#matriz_total = np.zeros((6,199))
#Wind
matriz = np.zeros((10,299))
matriz_total = np.zeros((6,299))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        print(datos)
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")        

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_entrenamiento/A
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
[0.00620925 0.00769617 0.00638461 0.00637137 0.00642438 0.00643115
 0.00639267 0.00639421 0.00639496 0.00639547 0.00639567 0.0063959
 0.00639595 0.00786066 0.00639612 0.00639627 0.00639634 0.00643912
 0.00639763 0.00644102 0.00639652 0.00639677 0.00639666 0.00639693
 0.006397   0.00640024 0.00639703 0.00639733 0.00639716 0.00782296
 0.00782819 0.00640961 0.00640921 0.00645645 0.0078886  0.0063975
 0.00647164 0.00639779 0.00647362 0.00655113 0.00663943 0.00639813
 0.00639858 0.00724009 0.00714218 0.00737346 0.00737907 0.00754006
 0.00940243 0.00802873 0.01096035 0.00639999 0.00956874 0.01060892
 0.01233494 0.00640139 0.02479735 0.04346022 0.08701325 0.20296962
 0.15913311 0.2253

[0.006209   0.00630088 0.00634767 0.00778229 0.00779689 0.00638943
 0.00639253 0.00639412 0.00639501 0.00639562 0.00639573 0.0063962
 0.00639601 0.00639611 0.00639652 0.00639619 0.00639668 0.00781332
 0.00639655 0.00644388 0.00639671 0.00781435 0.00639686 0.00639681
 0.00643673 0.00781524 0.00639701 0.00644391 0.00639715 0.00639892
 0.00639915 0.0063975  0.0078647  0.00643625 0.00640029 0.00639764
 0.00644475 0.00639761 0.00639785 0.00639792 0.00639813 0.00639822
 0.00639812 0.00644454 0.00639841 0.00639848 0.00643701 0.00639824
 0.00643736 0.00645554 0.00783581 0.00639871 0.00639855 0.00639903
 0.0063994  0.00639875 0.00788638 0.00639912 0.0064772  0.00792271
 0.00639931 0.00661079 0.00670711 0.00687265 0.00694107 0.00698331
 0.00702249 0.00640007 0.00744153 0.00800871 0.00977587 0.00640119
 0.00871941 0.00939559 0.01158991 0.01166685 0.01405495 0.01925659
 0.02350829 0.03138826 0.02651792 0.0310719  0.04633452 0.06107078
 0.04414698 0.09234099 0.08003984 0.09031978 0.06381432 0.07372

In [7]:
print(matriz_total)

[[0.00621526 0.00658035 0.00649969 ... 0.20813738 0.18837662 0.25455232]
 [0.00675969 0.00644644 0.00635154 ... 0.95647853 0.96863823 0.96562536]
 [0.00649267 0.00644715 0.00634774 ... 0.94346783 0.88299577 0.8121623 ]
 [0.00621336 0.00630414 0.00635881 ... 0.74328069 0.78533514 0.68915744]
 [0.00621134 0.00631015 0.00649201 ... 0.84703305 0.82516916 0.8960016 ]
 [0.00648658 0.006301   0.00649894 ... 0.18079533 0.23518583 0.23514076]]


In [8]:
print(vector_promedio)

[0.00648658 0.006301   0.00649894 0.00652045 0.00667842 0.006531
 0.00667572 0.00668606 0.0068242  0.00640362 0.00640429 0.00682572
 0.0064179  0.00667949 0.00640496 0.00640474 0.00654681 0.00668005
 0.00668005 0.00669389 0.00669778 0.00654274 0.00655133 0.00655192
 0.00640574 0.00655623 0.00682295 0.00653975 0.00641047 0.00653999
 0.00654378 0.00640168 0.00654475 0.00641165 0.00668303 0.00639848
 0.00641656 0.00640785 0.00698207 0.0064206  0.00668345 0.00641488
 0.0066851  0.00655256 0.00641519 0.00670189 0.00669279 0.0065505
 0.00656217 0.00641092 0.00670727 0.0065513  0.0068446  0.00643214
 0.0067124  0.00643848 0.00673906 0.00645655 0.00649301 0.00727474
 0.00653891 0.00713422 0.00679417 0.00680889 0.00691601 0.00754573
 0.00763176 0.00764154 0.00792063 0.00786431 0.00788857 0.00931868
 0.00938853 0.01055691 0.0113947  0.01266154 0.01791165 0.02540276
 0.03514745 0.05511953 0.06819884 0.08475638 0.11720783 0.14121491
 0.18363037 0.15844501 0.19981426 0.22042465 0.23022624 0.1781709

In [9]:
vector_promedio.shape

(299,)

In [10]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_A/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_A/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_A/A
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_A/A(1)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_A/A(2)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_A/A(4)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1

In [11]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_x/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_x/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_x/A
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_x/A(1)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_x/A(2)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1-4', '2-2(2)-2(1)-1-5', '2-2(2)-2(1)-1-6', '2-2(2)-2(1)-1-7', '2-2(2)-2(1)-1-8', '2-2(2)-2(1)-1-9', '2-2(2)-2(1)-1-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/datos_filtrados_pruebas_x/A(4)x
['2-2(2)-2(1)-1-1', '2-2(2)-2(1)-1-2', '2-2(2)-2(1)-1-3', '2-2(2)-2(1)-1