# Este código sirve para las BD con los archivos agrupados 

Lee los archivos agrupados en carpetas hechas por el código "extraer_datos.ipynb" 

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import os
import re
import matplotlib.pyplot as plt

In [2]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_entrenamiento/"
#Windows----VERIFICAR RUTA
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
#Linux
#matriz = np.zeros((10,199))
#matriz_total = np.zeros((6,199))
#Wind
matriz = np.zeros((10,299))
matriz_total = np.zeros((6,299))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        print(datos)
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")        

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento/A
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
[0.00620922 0.00630099 0.00634779 0.00641113 0.00779692 0.00643138
 0.00639264 0.00639426 0.00643764 0.00639565 0.00643857 0.0063962
 0.00643868 0.00639655 0.00781337 0.00639687 0.00639704 0.00786134
 0.00639741 0.00639762 0.00644066 0.00639808 0.00639703 0.0063986
 0.00639888 0.00639919 0.00639953 0.00639989 0.0064003  0.00644423
 0.00640166 0.00782365 0.00640244 0.00640356 0.00640498 0.00640667
 0.00640597 0.0064101  0.00640865 0.00641348 0.00645937 0.00639913
 0.00641859 0.00784626 0.00785252 0.0064888  0.00646356 0.00648002
 0.00652661 0.00662608 0.00662174 0.00819118 0.00672967 0.00684642
 0.00688616 0.00703904 0.0073089  0.00748047 0.00743732 0.00780222
 0.00794885 0.00859947 0.00895134 0.00966898 0.01058423 0.013029
 0.01919257 0.02599939 0.05104886 0.04652261 

[0.00620924 0.00630101 0.00634767 0.00637136 0.00638335 0.0063895
 0.00639262 0.00781022 0.00639508 0.00639563 0.00639594 0.00643836
 0.00643957 0.0078176  0.00639661 0.00781319 0.00639709 0.00639721
 0.00639718 0.00639733 0.00639739 0.006398   0.0078145  0.00639842
 0.00639735 0.00639876 0.00639861 0.00639882 0.00639905 0.0063993
 0.00786553 0.00644224 0.00640009 0.00640039 0.00640151 0.00644209
 0.00640138 0.00640175 0.00781982 0.00640239 0.00639927 0.0063994
 0.00782692 0.00640622 0.00640734 0.00640598 0.00640685 0.00640764
 0.00782755 0.00640049 0.00641078 0.00646001 0.00641417 0.00640106
 0.00641775 0.00784205 0.00642382 0.00642675 0.00647381 0.00643224
 0.00643722 0.00644277 0.00787889 0.00646931 0.00653391 0.0065033
 0.00651323 0.0065542  0.00658819 0.0066367  0.00666629 0.00679027
 0.00670465 0.00671475 0.00684443 0.00691946 0.00700222 0.00699838
 0.00721668 0.00741158 0.00759772 0.00809029 0.00820305 0.00865801
 0.00860823 0.00904549 0.0099137  0.01244032 0.01514978 0.01896645

In [3]:
print(matriz_total)

[[0.00635485 0.00645703 0.00649938 ... 0.34648929 0.34487882 0.34857452]
 [0.0063509  0.0063075  0.0063551  ... 0.95656729 0.94304935 0.95370583]
 [0.00648838 0.00644402 0.00648824 ... 0.9431687  0.93312132 0.95087738]
 [0.00621342 0.00631043 0.00634771 ... 0.86799278 0.84101949 0.74312842]
 [0.00648423 0.00645351 0.00635508 ... 0.92642206 0.9381132  0.9304802 ]
 [0.00634883 0.00686234 0.00651093 ... 0.25851778 0.25173343 0.23944608]]


In [4]:
print(vector_promedio)

[0.00634883 0.00686234 0.00651093 0.0065284  0.00667431 0.00669338
 0.00667573 0.00654006 0.00654948 0.00669209 0.00654131 0.00669324
 0.00668902 0.00641367 0.00655106 0.00654686 0.00640971 0.00640594
 0.00654299 0.00654801 0.00640175 0.00640563 0.00668623 0.00668603
 0.00654827 0.00668567 0.00654808 0.00669994 0.00640744 0.00669568
 0.00655975 0.0065504  0.00640794 0.00669363 0.00699601 0.00668825
 0.00668471 0.0064018  0.00683685 0.00640528 0.00641509 0.00669668
 0.00640324 0.00655446 0.00655966 0.00671082 0.00642423 0.00655309
 0.00641558 0.00671686 0.00671346 0.00698809 0.00670662 0.00655883
 0.0064283  0.00656259 0.00656839 0.00671788 0.00643341 0.00672494
 0.00644988 0.00660341 0.00645727 0.00660616 0.00648143 0.00666019
 0.00652059 0.00655572 0.00661384 0.00665845 0.00673263 0.00678566
 0.00681658 0.0073292  0.00710138 0.00714571 0.00731805 0.00731561
 0.00745317 0.00748494 0.00794534 0.00792645 0.00813771 0.00893991
 0.00914074 0.01037686 0.01102776 0.01187292 0.01424046 0.0183

In [5]:
vector_promedio.shape

(299,)

In [6]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_A/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/A
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/A(1)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/A(2)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/A(4)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A/Ax
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pru

In [7]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_x/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/A
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/A(1)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/A(2)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/A(4)x
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x/Ax
['red-1', 'red-2', 'red-3', 'red-4', 'red-5', 'red-6', 'red-7', 'red-8', 'red-9', 'red-10']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pru