# Este código sirve para las BD con los archivos agrupados 

Lee los archivos de los pesos que están agrupados en carpetas hechas por el código "extraer_datos_redes_pesos.ipynb" 

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import os
import re
import matplotlib.pyplot as plt

In [36]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_entrenamiento/"
#Windows----VERIFICAR RUTA
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
#Linux
#matriz = np.zeros((10,199))
#matriz_total = np.zeros((6,199))
#Wind
matriz = np.zeros((10,299))
matriz_total = np.zeros((6,299))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre2'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        #print(datos)
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre2' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre2' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre2' + '.txt', matriz_total.T, fmt="%s")       

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/A/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/A(1)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/A(2)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/A(4)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 're

In [37]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_entrenamiento/"
#Windows----VERIFICAR RUTA
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
#Linux
#matriz = np.zeros((10,199))
#matriz_total = np.zeros((6,199))
#Wind
matriz = np.zeros((10,299))
matriz_total = np.zeros((6,299))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre1'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        print(datos)
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre1' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre1' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre1' + '.txt', matriz_total.T, fmt="%s")        

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_entrenamiento_PESOS/A/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
[0.25350171 0.37595439 0.43755092 0.46852667 0.48411811 0.49196063
 0.49591126 0.49789061 0.49889088 0.49945017 0.49966852 0.49979343
 0.49985575 0.49989378 0.49990817 0.49991867 0.49992506 0.49992469
 0.49992369 0.49993399 0.49993161 0.49993879 0.49993791 0.49994194
 0.49993766 0.49993638 0.49993657 0.49993409 0.49993569 0.49994684
 0.49994537 0.49994492 0.4999396  0.4999407  0.49994102 0.49994166
 0.49994423 0.49994966 0.4999514  0.49994833 0.49995389 0.49995212
 0.49996258 0.49995631 0.49996046 0.49996579 0.49997365 0.49997264
 0.49998087 0.4999866  0.50000738 0.50000923 0.50002107 0.50003628
 0.50006787 0.50010913 0.50012408 0.50015662 0.50018641 0.5002391
 0.50025473 0.50028378 0.50030036 0.50034371 0.5

[0.25316585 0.37576682 0.43743395 0.46846169 0.48406792 0.49192185
 0.49587468 0.49766261 0.49866073 0.4991605  0.49941417 0.49953822
 0.49960236 0.49963671 0.49966649 0.4996677  0.49967479 0.49967874
 0.49967846 0.4996837  0.49967781 0.49968129 0.49967561 0.4996808
 0.49967193 0.4996712  0.49967283 0.49967153 0.49965973 0.49966873
 0.49966932 0.49967183 0.49967018 0.49967436 0.49967394 0.49967368
 0.49967071 0.49967583 0.49968062 0.49968398 0.49968221 0.49968099
 0.49968593 0.49969463 0.4996922  0.49969166 0.49968971 0.49969431
 0.49970422 0.49970932 0.49971635 0.49973149 0.49973917 0.49975006
 0.49976669 0.49978234 0.49982716 0.4998572  0.49988122 0.49992562
 0.49994304 0.49995643 0.499972   0.50001332 0.49998798 0.50000538
 0.49967605 0.49899783 0.49942547 0.49682802 0.49070319 0.48779629
 0.48456779 0.46101008 0.43727452 0.44630189 0.46651783 0.41973892
 0.44733948 0.38746857 0.42028696 0.44646061 0.41263584 0.34361378
 0.38822914 0.38388986 0.4248453  0.40030401 0.39597937 0.33652

In [38]:
print(matriz_total)

[[0.24858519 0.36750517 0.42713512 ... 0.45191643 0.45332135 0.45579042]
 [0.24860993 0.37116549 0.4319713  ... 0.43995207 0.45185102 0.44246856]
 [0.25585709 0.3781865  0.44082436 ... 0.48455651 0.4962934  0.523101  ]
 [0.253489   0.37588734 0.43746626 ... 0.47419148 0.47023512 0.47877047]
 [0.25104025 0.37353024 0.43474628 ... 0.51252803 0.51473872 0.50960024]
 [0.25834369 0.38309989 0.44585769 ... 0.4951682  0.49502382 0.4950645 ]]


In [39]:
print(vector_promedio)

[0.25834369 0.38309989 0.44585769 0.47742289 0.49315093 0.50106191
 0.50512313 0.50712582 0.50814273 0.50866166 0.50891563 0.50904371
 0.5091072  0.50913812 0.50915434 0.50916217 0.50916656 0.50916818
 0.50916893 0.50916861 0.50916756 0.50916914 0.50917048 0.50917255
 0.50917098 0.50917192 0.50917153 0.50917224 0.5091715  0.50917212
 0.50917098 0.50917218 0.50917209 0.50917125 0.50917067 0.50916924
 0.5091694  0.50916666 0.50916498 0.5091654  0.50916506 0.50916096
 0.5091594  0.50915979 0.50915969 0.50915667 0.50915575 0.50915487
 0.50915598 0.50915362 0.50915314 0.50915095 0.50915047 0.50914736
 0.50914566 0.50914154 0.50913924 0.5091366  0.50913121 0.50912618
 0.50912047 0.50911776 0.5091115  0.50910356 0.50909174 0.50908279
 0.50907163 0.50905786 0.50904139 0.50901963 0.5089991  0.5089724
 0.50894569 0.50891585 0.50888651 0.50885164 0.50881658 0.50877931
 0.50874302 0.50870141 0.50866125 0.50861799 0.50857515 0.5085284
 0.50847936 0.50842734 0.50837505 0.50832391 0.50826553 0.508204

In [40]:
vector_promedio.shape

(299,)

In [41]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_A/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre1'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre1' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre1' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre1' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(1)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(2)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(4)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/U

In [42]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_A/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre2'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre2' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre2' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre2' + '.txt', matriz_total.T, fmt="%s")  

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(1)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(2)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_A_PESOS/A(4)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/U

In [43]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_x/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre1'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre1' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre1' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre1' + '.txt', matriz_total.T, fmt="%s")    

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(1)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(2)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(4)x/Pre1
['red-1-Pre1', 'red-2-Pre1', 'red-3-Pre1', 'red-4-Pre1', 'red-5-Pre1', 'red-6-Pre1', 'red-7-Pre1', 'red-8-Pre1', 'red-9-Pre1', 'red-10-Pre1']
C:/U

In [44]:
#Linux
#ubicacion_original = "/home/yan/datos_redes_tesis_doctorado/Con ITI/2-2(2)-2(1)-1 parcialmente/datos_filtrados_pruebas_x/"
#Windows
ubicacion_original = 'C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/'
archivo_promedios = ubicacion_original + 'PROMEDIOS'
archivo_promedios_total = ubicacion_original + 'PROMEDIOS_total'
archivo_error = ubicacion_original + 'ERROR'
matriz = np.zeros((10,19))
matriz_total = np.zeros((6,19))
i = 0
j = 0


def sorted_aphanumeric(contenido):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(contenido, key=alphanum_key)


carpetas = sorted_aphanumeric(os.listdir(ubicacion_original))
print(carpetas)

for carpeta in carpetas:
    ruta_carpetas = ubicacion_original + carpeta + '/Pre2'
    print(ruta_carpetas)
    
    archivos = sorted_aphanumeric(os.listdir(ruta_carpetas))
    print(archivos)
    
    for archivo in archivos:
        ruta_archivo = ruta_carpetas + '/' + archivo
        datos = np.loadtxt(ruta_archivo)
        #datos = pd.read_csv(ruta_archivo, sep = ': ', engine='python', keep_default_na=False,
         #       na_values=[' '])
        
        matriz[i][:] = datos
        i += 1
        
    
    vector_promedio = np.mean(matriz, axis=0)
    vector_error = stats.sem(matriz, axis=0, ddof=0)
        
    np.savetxt(archivo_promedios + '_' + carpeta + 'Pre2' + '.txt', vector_promedio, fmt="%s")
    np.savetxt(archivo_error + '_' + carpeta + 'Pre2' + '.txt', vector_error, fmt="%s")
    i = 0
    
    matriz_total[j][:] = vector_promedio
    j +=1

matriz_total.T
np.savetxt(archivo_promedios_total + '_Pre2' + '.txt', matriz_total.T, fmt="%s")   

['A', 'A(1)x', 'A(2)x', 'A(4)x', 'Ax', 'x']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(1)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(2)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/Users/yanoj/OneDrive/Documentos/simulacion/con ITI/datos_filtrados_pruebas_x_PESOS/A(4)x/Pre2
['red-1-Pre2', 'red-2-Pre2', 'red-3-Pre2', 'red-4-Pre2', 'red-5-Pre2', 'red-6-Pre2', 'red-7-Pre2', 'red-8-Pre2', 'red-9-Pre2', 'red-10-Pre2']
C:/U